name: My Action

on:
  push:
    branches:
      - main

jobs:
  my-job:
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Make HTTP request
        uses: actions/http-client@v2.2.0
        with:
          url: https://api.github.com/repos/owner/repo/code-scanning/alerts/settings
          method: PUT
          headers: |
            {
              "Content-Type": "application/json",
              "Authorization": "Bearer ${{ secrets.TOKEN }}"
            }
          body: |
            {
              "code_scanning": {
                "alert_severity": "high"
              }
            }
      - name: Log response status code
        run: echo ${{ steps.http-client.outputs.status-code }}
