name: Update Readme

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          echo "${GPG_PRIVATE_KEY}" | gpg --batch --import
          echo "${PASSPHRASE}" | gpg --batch --passphrase-fd 0 --pinentry-mode loopback --import-ownertrust
        

      - name: Set up Git
        env:
          GPG_TTY: $(tty)
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        run: |
          git config commit.gpgsign true
          git config user.signingkey $GPG_KEY_ID
          git config --global user.email ${{ secrets.GIT_COMMITTER_EMAIL }}
          git config --global user.name ${{ secrets.GIT_COMMITTER_NAME }}

      - name: Update Readme
        run: |
          echo "This is an updated readme." >> README.md
          git add README.md
          git commit -S -m "chore: update README.md"
          git push
