name: Update Readme

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4       

      - name: Import GPG key
        run: |
          gpg --version

          cd $GITHUB_WORKSPACE

          echo "${GPG_PRIVATE_KEY}" | gpg --batch --import

          echo "${PASSPHRASE}" | gpg --batch --passphrase-fd 0 --pinentry-mode loopback
          
          export GPG_TTY=$(tty)

          echo "test" > file.txt
          gpg -u $GPG_KEY_ID --armor --detach-sign -o signature.gpg file.txt
        env:
            GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
            PASSPHRASE: ${{ secrets.PASSPHRASE }}
            GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        working-directory: ${{ github.workspace }}



 
