name: Distribute YML Files

on:
  issues:
    types:
      - opened
      - edited

# expected issue body input should be structured as follows:
  #     {
  #         "rep01": {
  #             "repository": "rep01",
  #             "organisation": "org01"
  #         },
  #         "rep02": {
  #             "repository": "rep02",
  #             "organisation": "org02"
  #         } 
  #     }

jobs:
  distribute-yml-files:
    runs-on: ubuntu-latest
    strategy:  
      matrix:
        repository: ${{ fromJson(github.event.issue.body).*.repository }}  # rep01, repo02
      max-parallel: 1
    steps:
      - name: Checkout central repository
        uses: actions/checkout@v4

      - name: Setup git
        run: |
            git config commit.gpgsign true
            git config user.signingkey $GPG_KEY_ID
            git config gpg.program /tmp/gpg.sh
            git config user.email ${{ secrets.GIT_COMMITTER_EMAIL }}
            git config user.name ${{ secrets.GIT_COMMITTER_NAME }}
        env:
            GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

      - name: Check YML Files
        run: |
            repo='${{ matrix.repository }}'
            owner='${{ fromJSON(github.event.issue.body)[matrix.repository].organisation }}'
            echo "Processing repository: $owner/$repo"
            
            branch="main"

            for file in files/*.yml; do
              workflow_file=".github/workflows/$(basename "$file")"
              existing_file=$(curl -s -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GK_PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/$owner/$repo/contents/$workflow_file?ref=$branch")
              echo "$existing_file"
            done

