name: Distribute YML Files

on:
  issues:
    types:
      - opened
      - edited

# expected issue body input should be structured as follows:
  #     {
  #         "rep01": {
  #             "repository": "rep01",
  #             "organisation": "org01"
  #         },
  #         "rep02": {
  #             "repository": "rep02",
  #             "organisation": "org02"
  #         } 
  #     }

jobs:
  distribute-yml-files:
    runs-on: ubuntu-latest
    strategy:  
      matrix:
        repository: ${{ fromJson(github.event.issue.body).*.repository }}  # rep01, repo02
      max-parallel: 1
    steps:
      - name: Checkout central repository
        uses: actions/checkout@v4

      - name: Setup git
        run: |
            git config commit.gpgsign true
            git config user.signingkey $GPG_KEY_ID
            git config gpg.program /tmp/gpg.sh
            git config user.email ${{ secrets.GIT_COMMITTER_EMAIL }}
            git config user.name ${{ secrets.GIT_COMMITTER_NAME }}
        env:
            GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

    #   - name: Check YML Files
    #     uses: actions/github-script@v6
    #     with:
    #       github-token: ${{ secrets.GK_PAT }}
    #       script: |
    #         const repo = '${{ matrix.repository }}';
    #         const owner = '${{ fromJSON(github.event.issue.body)[matrix.repository].organisation }}';
    #         console.log(`Processing repository: ${owner}/${repo}`);
                    
    #         const branch = 'github-migration';
        
    #         for (const filePath of ['files/github-rest-api12.yml']) {
    #             const fileName = filePath.split('/').pop(); // Extracts only the file name
    #             const workflow_file = `.github/workflows/${fileName}`

    #             console.log(`Workflow File: ${workflow_file}`);
    #             console.log(`File Name: ${fileName}`);

    #             const response = await github.rest.repos.getContent({
    #               owner: owner,
    #               repo: repo,
    #               path: workflow_file,
    #               ref: branch
    #             });
    #             console.log(response.data);
    #         }
          
      - name: Check and Copy YML Files
        run: |
            repo='${{ matrix.repository }}'
            owner='${{ fromJSON(github.event.issue.body)[matrix.repository].organisation }}'
            echo "Processing repository: $owner/$repo"
            
            branch="github-migration"

            for file in files/*.yml; do
                workflow_file=".github/workflows/$(basename "$file")"
                existing_file=$(curl -s -o /dev/null -w "%{http_code}" \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GK_PAT }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "https://api.github.com/repos/$owner/$repo/contents/$workflow_file?ref=$branch")

                # If the HTTP status code is 404 (Not Found), proceed to create it
                if [ "$existing_file" -eq 404 ]; then
                  echo "File does not exist. Creating..."
                else
                  echo "File already exists. Skipping..."
                fi
            done
